name: Telegram Listener

on:
  workflow_dispatch:

jobs:
  listen:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyrogram tgcrypto requests

      - name: Start Telegram Listener
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          python - <<'EOF'
          import os
          import requests
          from pyrogram import Client, filters

          api_id = int(os.getenv("API_ID"))
          api_hash = os.getenv("API_HASH")
          session = os.getenv("SESSION_STRING")

          token = os.getenv("GH_TOKEN")
          repo = os.getenv("REPO")

          print("✅ Listener starting...", flush=True)

          app = Client(
              "listener",
              api_id,
              api_hash,
              session_string=session
          )

          def trigger_worker(link):
              url = f"https://api.github.com/repos/{repo}/dispatches"

              r = requests.post(
                  url,
                  headers={
                      "Authorization": f"token {token}",
                      "Accept": "application/vnd.github+json"
                  },
                  json={
                      "event_type": "telegram_video",
                      "client_payload": {"link": link}
                  }
              )

              print("Dispatch:", r.status_code, flush=True)

          @app.on_message(filters.all)
          async def handler(client, message):

              if not (
                  message.video
                  or message.document
                  or message.animation
                  or message.media_group_id
              ):
                  return

              if not message.link:
                  print("⚠️ No public link", flush=True)
                  return

              print("🚀 Trigger:", message.link, flush=True)
              trigger_worker(message.link)

          print("✅ Listener ready", flush=True)
          app.run()
          EOF
